FORMAT: 1A

# Fake Online REST API

## Group Posts

### /posts/1

#### Retrieve one post [GET]

+ Relation: posts-getposts

+ Response 200 (application/json; charset=utf-8)

    OK

    + Attributes
        - userId: 1 (number, fixed)
        - id: 1 (number, fixed)
        - title: `sunt aut facere repellat provident occaecati excepturi optio reprehenderit` (fixed)
        - body: quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto