FORMAT: 1A

# Fake Online REST API

## Group Posts

### /posts/89

#### Retrieve one post [GET]

+ Relation: posts-getposts

+ Response 200 (application/json; charset=utf-8)

    OK

    + Attributes
        - userId: 9 (number, fixed)
        - id: 89 (number, fixed)
        - title: `sint soluta et vel magnam aut ut sed qui` (fixed)
        - body (fixed)
            - sample
                repellat aut aperiam totam temporibus autem et
                architecto magnam ut
                consequatur qui cupiditate rerum quia soluta dignissimos nihil iure
                tempore quas est