FORMAT: 1A

# Fake Online REST API

## Group Comments

### /comments

#### Retrieve a list of comments [GET]

+ Relation: comments-getcomments

+ Response 200 (application/json; charset=utf-8)

    OK

    + Body
    
            [
              {
                "postId": 1,
                "id": 1,
                "name": "id labore ex et quam laborum",
                "email": "Eliseo@gardner.biz",
                "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
              }
            ]

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "postId": {
                    "type": "integer"
                  },
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "pattern": "^[a-zA-Z_.]+@[a-z.]+\\.[a-z]{1,}$"
                  },
                  "body": {
                    "type": "string"
                  }
                },
                "required": [
                  "postId",
                  "id",
                  "name",
                  "email",
                  "body"
                ]
              }
            }